# Generated by Django 4.2.6 on 2023-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_amout_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_fraudlent',
            field=models.BooleanField(default=False),
        ),
    ]
