# Generated by Django 4.2.6 on 2023-10-22 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_is_fraudlent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
