# Generated by Django 4.2.6 on 2023-10-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudAlert',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='country',
        ),
    ]
