# Generated by Django 4.2.6 on 2023-10-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transaction_is_fraudlent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
