# Generated by Django 4.2.6 on 2023-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_set', to='auth.permission'),
        ),
    ]
